version: '3.8'

services:
  postgres-propostaapi:
    image: postgres:latest
    container_name: postgres-propostaapi
    restart: always
    environment:
      POSTGRES_DB: PropostaAPIDocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata_propostaapi:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-propostaapi
    restart: always
    ports:
      - "5673:5672"     # Porta para conexão de aplicações (troquei de 5672 para 5673)
      - "15673:15672"   # Porta do painel de administração web (troquei de 15672 para 15673)
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  pgdata_propostaapi:

